export const P1_Label = {
  EN: {
    ASD_DEF_TITLE: "What is Austism Spectrum Disorder?",
    ASD_DEF: "Autism spectrum disorder is a neurodevelopmental condition. It affects individuals’ communication, social interaction, and behavior.",
    ASD_CLASSIFICATION_TITLE: "Classification of Autism Spectrum Disorder",
    ASD_CLASSIFICATION1: "Classic Autism: Difficulties in social interaction and communication, also characterized  by repetitive behavior and limited interests",
    ASD_CLASSIFICATION2: "Asperger Syndrome: Has typically normal language and cognitive development but has difficulty with social interaction",
    ASD_CLASSIFICATION3: "Childhood Disintegrative Disorder: A rare condition that develops normally in the first two to three years of life, then suddenly regresses in areas such as language, social skills, and motor abilities",
    ASD_CLASSIFICATION4: "Pervasive Developmental Disorder - Not Otherwise Specified (PDD-NOS): Show some symptoms of autism but does not meet all the criteria to be diagnosed with classic autism or Aspergers",
    ASD_CAUSE_TITLE: "Causes",
    ASD_CAUSE_DEF: "Researchers have not been able to pinpoint the exact causes of this disorder but research suggests that a combination of genetic and environmental factors may be the underlying cause",
    ASD_CAUSE_DEF1: "Genetics: Genetic mutations account for only a small percentage of cases but study has shown that autism tends to run in families as a genetic trait",
    ASD_CAUSE_DEF2: "Environmental factors: Exposure to certain toxins or drugs during pregnancy, advanced parental age, parental infections, and complications during  birth are all possible factors that can potentially increase the risk of autism",
    ASD_CAUSE_DEF3: "Brain Development: Abnormalities in brain anatomy and activity patterns have been discovered compared to those without the disorder",
    ASD_CAUSE_DEF4: "Neurotransmitter Imbalances: Abnormalities in neurotransmitters, chemicals that deliver signals to the brain, can be the potential cause ",
    ASD_SYMPTOMS_TITLE: "Symptoms",
    ASD_SYMPTOMS_DEF: "It is important to note that individuals with autism spectrum disorder may not experience all these symptoms as they vary widely in the spectrum. If you are concerned your child has autism, it is best that you speak to a ",
    ASD_SYMPTOMS_LINK: "professional",
    ASD_SYMPTOMS_DEF1: "Difficulty in social communication and interaction: Has trouble with eye contact, body language, understanding social cues, and initiating/managing conversations",
    ASD_SYMPTOMS_DEF2: "Repetitive behaviors or routines: Repetitive behavior helps them feel a sense of comfort. Some typical examples include lining up toys, flapping hands, repeating phrases, and so on",
    ASD_SYMPTOMS_DEF3: "Limited interest or activities: Individuals with autism spectrum disorder become very focused on specific topics or objects, which leads them to have limited interests or activities",
    ASD_SYMPTOMS_DEF4: "Sensory sensitivities: Having a strong aversion to certain sounds, textures, and lights",
    ASD_SYMPTOMS_DEF5: "Delay in language development: Late language development or non at all",
    ASD_SYMPTOMS_DEF6: "Difficulty in imaginative play: Showing difficulty in imaginative play such as pretending with toys or playing make-believe games",
    ASD_SYMPTOMS_DEF7: "Unusual behaviors: Showing unusual behavior such as spinning in circles and repetitively flicking finger",
    ASD_TREATMENTS_TITLE: "Treatments",
    ASD_TREATMENTS_DEF: "There is no current method that can fully cure autism but early intervention can enhance adaptive functioning.",
    ASD_TREATMENTS_DEF1: "Behavioral Therapy: Teaches new skills and modifying behaviors through positive reinforcement. Applied Behaviour Analysis (ABA) is an example of behavioral therapy",
    ASD_TREATMENTS_DEF2: "Speech and language therapy: Aims to improve communication and language kills",
    ASD_TREATMENTS_DEF3: "Occupational therapy: Aims to improve daily living and motor skills",
    ASD_TREATMENTS_DEF4: "Social skill training: Aims to teach social cues and develop social relationships",
    ASD_TREATMENTS_DEF5: "Medications: Used to manage symptoms such as hyperactivity, anxiety, or repetitive behavior",
  },
  VI: {
    ASD_DEF_TITLE: "Rối loạn phổ tự kỷ là gì?",
    ASD_DEF: "Rối loạn phổ tự kỷ là một tình trạng phát triển thần kinh. Nó ảnh hưởng đến giao tiếp, tương tác xã hội và hành vi của cá nhân.",
    ASD_CLASSIFICATION_TITLE: "Phân loại của rối loạn phổ tự kỷ",
    ASD_CLASSIFICATION1: "Phổ tự kỷ cổ điển: Khó khăn trong tương tác xã hội và giao tiếp, cũng như được đặc trưng bởi hành vi lặp đi lặp lại và sở thích hạn chế",
    ASD_CLASSIFICATION2: "Hội chứng Asperger: Thường có sự phát triển ngôn ngữ và nhận thức bình thường nhưng gặp khó khăn trong tương tác xã hội",
    ASD_CLASSIFICATION3: "Rối loạn suy giảm thời thơ ấu: Một tình trạng hiếm gặp phát triển bình thường trong hai đến ba năm đầu đời, sau đó đột ngột suy giảm ở các lĩnh vực như ngôn ngữ, kỹ năng xã hội và chức năng cơ bản",
    ASD_CLASSIFICATION4: "Rối loạn phát triển khác - Không được chỉ định cụ thể (PDD-NOS): Cho thấy một số triệu chứng của rối loạn phổ tự kỷ nhưng không đáp ứng đủ các tiêu chuẩn để chẩn đoán phổ tự kỷ cổ điển hoặc hội chứng Asperger",
    ASD_CAUSE_TITLE: "Nguyên nhân",
    ASD_CAUSE_DEF: "Các nhà nghiên cứu chưa thể xác định được nguyên nhân chính xác của rối loạn này, nhưng nghiên cứu cho thấy một sự kết hợp giữa các yếu tố di truyền và môi trường có thể là nguyên nhân tiềm ẩn",
    ASD_CAUSE_DEF1: "Di truyền học: Đột biến di truyền chỉ chiếm một phần nhỏ các trường hợp, nhưng nghiên cứu đã chỉ ra rằng phổ tự kỷ có xu hướng chạy trong gia đình như một đặc điểm di truyền",
    ASD_CAUSE_DEF2: "Những yếu tố môi trường: Tiếp xúc với một số độc tố hoặc thuốc trong thời kỳ mang thai, tuổi của bố mẹ cao, nhiễm trùng của bố mẹ, và các biến chứng trong quá trình sinh đều là các yếu tố có thể tăng nguy cơ mắc bệnh tự kỷ",
    ASD_CAUSE_DEF3: "Sự phát triển não: Những bất thường về giải phẫu và hoạt động của não đã được phát hiện so với những người không mắc bệnh này",
    ASD_CAUSE_DEF4: "Sự mất cân bằng chất truyền thần kinh: Những bất thường về chất truyền thần kinh, các chất hóa học mang tín hiệu đến não, có thể là nguyên nhân tiềm tàng",
    ASD_SYMPTOMS_TITLE: "Triệu chứng",
    ASD_SYMPTOMS_DEF: "Cần lưu ý rằng những người mắc chứng tự kỷ có thể không trải qua tất cả các triệu chứng này vì chúng thay đổi rộng rãi trên phổ. Nếu bạn lo lắng con bạn mắc chứng tự kỷ, tốt nhất là bạn nói chuyện với một ",
    ASD_SYMPTOMS_LINK: "chuyên gia",
    ASD_SYMPTOMS_DEF1: "Khó khăn trong giao tiếp và tương tác xã hội: Gặp khó khăn trong liên hệ mắt, ngôn ngữ cơ thể, hiểu các dấu hiệu xã hội và khởi động/quản lý các cuộc trò chuyện",
    ASD_SYMPTOMS_DEF2: "Hành vi hoặc thói quen lặp đi lặp lại: Hành vi lặp đi lặp lại giúp họ cảm thấy thoải mái. Một số ví dụ điển hình bao gồm xếp đồ chơi, vỗ tay nhịp nhàng, lặp lại các câu nói và vân vân",
    ASD_SYMPTOMS_DEF3: "Sở thích hoặc hoạt động hạn chế: Những người mắc chứng tự kỷ trở nên rất tập trung vào các chủ đề hoặc đồ vật cụ thể, dẫn đến họ có sở thích hoặc hoạt động hạn chế",
    ASD_SYMPTOMS_DEF4: "Nhạy cảm với các giác quan: Có khuynh hướng rất ghét những âm thanh, kết cấu và ánh sáng nhất định",
    ASD_SYMPTOMS_DEF5: "Chậm phát triển ngôn ngữ: Phát triển ngôn ngữ muộn hoặc không phát triển chút nào",
    ASD_SYMPTOMS_DEF6: "Khó khăn trong trò chơi sáng tạo: Thể hiện khó khăn trong trò chơi sáng tạo như giả vờ với đồ chơi hoặc chơi các trò chơi tưởng tượng",
    ASD_SYMPTOMS_DEF7: "Hành vi bất thường: Thể hiện hành vi bất thường như quay tròn và lặp lại việc nhấp ngón tay",
    ASD_TREATMENTS_TITLE: "Các phương pháp điều trị",
    ASD_TREATMENTS_DEF: "Hiện tại không có phương pháp nào có thể chữa trị hoàn toàn tự kỷ nhưng can thiệp sớm có thể tăng cường chức năng thích ứng.",
    ASD_TREATMENTS_DEF1: "Therapy hành vi: Dạy kỹ năng mới và thay đổi hành vi thông qua củng cố tích cực. Phân tích hành vi ứng dụng (ABA) là một ví dụ về therapy hành vi",
    ASD_TREATMENTS_DEF2: "Therapy nói và ngôn ngữ: Nhằm mục đích cải thiện giao tiếp và kỹ năng ngôn ngữ",
    ASD_TREATMENTS_DEF3: "Therapy nghề nghiệp: Nhằm mục đích cải thiện kỹ năng sống hàng ngày và kỹ năng vận động",
    ASD_TREATMENTS_DEF4: "Đào tạo kỹ năng xã hội: Nhằm mục đích dạy các dấu hiệu xã hội và phát triển mối quan hệ xã hội",
    ASD_TREATMENTS_DEF5: "Thuốc: Sử dụng để quản lý các triệu chứng như sự hưng phấn, lo lắng hoặc hành vi lặp đi lặp lại",
  }
}



